apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-image-updater 
  project: default
  source:
    chart: argocd-image-updater
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.12.0
    helm:
      releaseName: argocd-image-updater
  syncPolicy:
    automated:
      prune: true
      selfHeal: true