apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: blog
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: blog
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - 'https://github.com/btrepp/home.git'
---

apiVersion: v1
kind: Namespace
metadata:
  name: blog

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: blog
  project: blog
  source:
    path: apps/blog
    repoURL: https://github.com/btrepp/home.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true