apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dash
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'dash'
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - 'https://kubernetes.github.io/dashboard/'
  
---
apiVersion: v1
kind: Namespace
metadata:
  name: dash

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: view-user
  namespace: dash

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: view-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dashboard-viewonly
subjects:
- kind: ServiceAccount
  name: view-user
  namespace: dash

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dash
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dash
  project: dash
  source:
    chart: kubernetes-dashboard
    repoURL: https://kubernetes.github.io/dashboard/
    targetRevision: 5.3.1
    helm:
      releaseName: kubernetes-dashboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true