apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tunnel
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'tunnel'
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - 'https://git.sr.ht/~btrepp/infrastructure'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tunnel
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tunnel
  project: tunnel
  source:
    path: apps/tunnel
    repoURL: 'https://git.sr.ht/~btrepp/infrastructure'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true