apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  labels:
    app: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: registry.concernedturtle.com/btrepp/blog
        imagePullSecrets:
        - name: registry-credentials
        ports:
        - containerPort: 80