apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dash-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dash
  project: dash
  source:
    chart: kubernetes-dashboard
    repoURL: https://kubernetes.github.io/dashboard/
    targetRevision: 5.3.1
    helm:
      releaseName: kubernetes-dashboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true