---
# tasks file for rpi-cgroups
- name: Enable container features
  become: yes
  register: cgroup_features
  replace:
    path: /boot/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
  - "cgroup_enable=cpuset"
  - "cgroup_memory=1"
  - "cgroup_enable=memory"

- name: Reboot if changed
  when: cgroup_features is changed
  become: yes
  reboot: